#!/usr/bin/env bash
# Convert a Mullvad WireGuard config into the env file gluetun expects.
#
# Usage: scripts/mullvad-wg-to-env.sh <mullvad-xx-yyy-wg-NNN.conf> [output]
# Default output: docker/mullvad.env (gitignored)

set -euo pipefail

src="${1:-}"
out="${2:-$(dirname "$0")/../docker/mullvad.env}"

if [[ -z "$src" || ! -f "$src" ]]; then
  echo "usage: $0 <mullvad-wireguard.conf> [output-env-file]" >&2
  exit 1
fi

# Pull the two values gluetun needs out of the [Interface] section.
private_key="$(sed -n 's/^[[:space:]]*PrivateKey[[:space:]]*=[[:space:]]*//p' "$src" | head -1)"
addresses="$(sed -n 's/^[[:space:]]*Address[[:space:]]*=[[:space:]]*//p' "$src" | head -1 | tr -d '[:space:]')"

if [[ -z "$private_key" || -z "$addresses" ]]; then
  echo "error: no PrivateKey/Address found in $src - is this a Mullvad WireGuard config?" >&2
  exit 1
fi

# Keep only the IPv4 address. Docker runs without IPv6 by default, and gluetun
# refuses to start on an IPv6 interface address it cannot support:
#   "interface address is IPv6 but IPv6 is not supported"
# If you enable IPv6 in the Docker daemon, append the fc00:bbbb:... address back.
ipv6="$(tr ',' '\n' <<< "$addresses" | grep ':' || true)"
addresses="$(tr ',' '\n' <<< "$addresses" | grep -v ':' | paste -sd, -)"

if [[ -z "$addresses" ]]; then
  echo "error: no IPv4 address found in $src" >&2
  exit 1
fi

# Mullvad names its configs mullvad-<hostname>.conf, e.g. mullvad-de-ber-wg-001.conf
hostname="$(basename "$src" .conf)"
hostname="${hostname#mullvad-}"

mkdir -p "$(dirname "$out")"
umask 077
cat > "$out" <<EOF
# Generated by scripts/mullvad-wg-to-env.sh from $(basename "$src")
# Contains a private key - never commit this file.
WIREGUARD_PRIVATE_KEY=$private_key
WIREGUARD_ADDRESSES=$addresses
SERVER_HOSTNAMES=$hostname
${ipv6:+# IPv6 address from the config, unused unless Docker has IPv6 enabled:
#WIREGUARD_ADDRESSES=$addresses,$ipv6}
EOF

chmod 600 "$out"
echo "wrote $out (server: $hostname)"
echo "next: docker compose run --rm xstream-tui"
